"""make points as float

Revision ID: 073b0a98b8ea
Revises: 61d0e94eec59
Create Date: 2026-06-18 23:23:15.026773
"""
from alembic import op
import sqlalchemy as sa


revision = '073b0a98b8ea'
down_revision = '61d0e94eec59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
