"""Ajout du module inscription centre de formation

Revision ID: 078d27cb471f
Revises: d8810f99fc3d
Create Date: 2026-07-30 18:08:28.548836
"""
from alembic import op
import sqlalchemy as sa


revision = '078d27cb471f'
down_revision = 'd8810f99fc3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursus',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('start_level', sa.Enum('A1', 'A2', 'B1', 'B2', name='cursus_level'), nullable=False),
    sa.Column('target_level', sa.Enum('A1', 'A2', 'B1', 'B2', name='cursus_level'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='cursus_status'), server_default='in_progress', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursus_branch_id'), 'cursus', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cursus_student_id'), 'cursus', ['student_id'], unique=False)
    op.create_table('level_enrollments',
    sa.Column('cursus_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', name='cursus_level'), nullable=False),
    sa.Column('inscription_fee_amount', sa.Integer(), nullable=False),
    sa.Column('formation_fee_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_inscription', 'active', 'completed', 'abandoned', name='level_enrollment_status'), server_default='pending_inscription', nullable=False),
    sa.Column('invoice_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cursus_id'], ['cursus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_enrollments_cursus_id'), 'level_enrollments', ['cursus_id'], unique=False)
    op.create_table('formation_payments',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('payment_type', sa.Enum('inscription', 'formation', name='formation_payment_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['level_enrollments.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_formation_payments_enrollment_id'), 'formation_payments', ['enrollment_id'], unique=False)
    op.add_column('center_licenses', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('center_licenses', sa.Column('logo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('center_licenses', 'logo_path')
    op.drop_column('center_licenses', 'address')
    op.drop_index(op.f('ix_formation_payments_enrollment_id'), table_name='formation_payments')
    op.drop_table('formation_payments')
    op.drop_index(op.f('ix_level_enrollments_cursus_id'), table_name='level_enrollments')
    op.drop_table('level_enrollments')
    op.drop_index(op.f('ix_cursus_student_id'), table_name='cursus')
    op.drop_index(op.f('ix_cursus_branch_id'), table_name='cursus')
    op.drop_table('cursus')
    # ### end Alembic commands ###
