"""Ajout features aux plans

Revision ID: 0ba33ac2fb38
Revises: 5671a7f7775d
Create Date: 2026-07-10 04:27:00.909926
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0ba33ac2fb38'
down_revision = '5671a7f7775d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'features')
    # ### end Alembic commands ###
