"""add_ai_credit_purchases_and_manual_payment

Revision ID: 1042b1111b0f
Revises: 1d8f57324fd6
Create Date: 2026-06-16 02:47:44.719142
"""
from alembic import op
import sqlalchemy as sa


revision = '1042b1111b0f'
down_revision = '1d8f57324fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credit_purchases',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_credit_purchases_payment_id'), 'ai_credit_purchases', ['payment_id'], unique=True)
    op.create_index(op.f('ix_ai_credit_purchases_user_id'), 'ai_credit_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_credit_purchases_user_id'), table_name='ai_credit_purchases')
    op.drop_index(op.f('ix_ai_credit_purchases_payment_id'), table_name='ai_credit_purchases')
    op.drop_table('ai_credit_purchases')
    # ### end Alembic commands ###
