"""mise a jour des schereinben

Revision ID: 12c907c04f8f
Revises: c840a0a3d563
Create Date: 2026-07-16 23:21:28.311723
"""
from alembic import op
import sqlalchemy as sa


revision = '12c907c04f8f'
down_revision = 'c840a0a3d563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('simulator_results_subject_id_fkey'), 'simulator_results', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('simulator_results_subject_id_fkey'), 'simulator_results', 'schreiben_subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
