"""add ai_credits to users

Revision ID: 1d8f57324fd6
Revises: 55048e03cf39
Create Date: 2026-06-03 03:24:19.559359
"""
from alembic import op
import sqlalchemy as sa


revision = '1d8f57324fd6'
down_revision = '55048e03cf39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_credits', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_credits')
    # ### end Alembic commands ###
