"""add address and logo_path to centers (fix)

Revision ID: 25af0e35520d
Revises: bd7bc7271eb5
Create Date: 2026-07-30 21:15:07.232608
"""
from alembic import op
import sqlalchemy as sa


revision = '25af0e35520d'
down_revision = 'bd7bc7271eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('center_licenses', 'logo_path')
    op.drop_column('center_licenses', 'address')
    op.add_column('centers', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('logo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'logo_path')
    op.drop_column('centers', 'address')
    op.add_column('center_licenses', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('center_licenses', sa.Column('logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
