"""Mise a jour du modele schereiben

Revision ID: 274741988f28
Revises: ba89e9011c1e
Create Date: 2026-08-04 03:10:26.516967
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '274741988f28'
down_revision = 'ba89e9011c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('floor_reached', sa.Boolean(), nullable=True))
    op.add_column('corrections', sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('corrections', sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('corrections', 'kohaesion_score')
    op.drop_column('corrections', 'criteria_feedbacks')
    op.drop_column('corrections', 'wortschatz_score')
    op.drop_column('corrections', 'aufgabe_score')
    op.drop_column('corrections', 'task_feedbacks')
    op.drop_column('corrections', 'grammatik_score')
    op.drop_constraint(op.f('exam_session_answers_question_id_fkey'), 'exam_session_answers', type_='foreignkey')
    op.create_foreign_key(None, 'exam_session_answers', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('exam_sessions_subject_id_fkey'), 'exam_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_sessions', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('sprechen_sessions_subject_id_fkey'), 'sprechen_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sprechen_sessions', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprechen_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sprechen_sessions_subject_id_fkey'), 'sprechen_sessions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('exam_sessions_subject_id_fkey'), 'exam_sessions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_session_answers', type_='foreignkey')
    op.create_foreign_key(op.f('exam_session_answers_question_id_fkey'), 'exam_session_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.add_column('corrections', sa.Column('grammatik_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('task_feedbacks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('aufgabe_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('wortschatz_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('criteria_feedbacks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('corrections', sa.Column('kohaesion_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('corrections', 'tasks')
    op.drop_column('corrections', 'criteria')
    op.drop_column('corrections', 'floor_reached')
    # ### end Alembic commands ###
