"""add_subjects_table

Revision ID: 2c18adbd9c10
Revises: 17ea0c21a600
Create Date: 2026-04-20 15:41:13.467221
"""
from alembic import op
import sqlalchemy as sa


revision = '2c18adbd9c10'
down_revision = '17ea0c21a600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('subject_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'subject_number', name='uq_subject_level_number')
    )
    op.create_index(op.f('ix_subjects_level_id'), 'subjects', ['level_id'], unique=False)
    op.add_column('exam_sessions', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_exam_sessions_subject_id'), 'exam_sessions', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'exam_sessions', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.add_column('modules', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_modules_level_id'), table_name='modules')
    op.drop_constraint(op.f('uq_module_level_slug'), 'modules', type_='unique')
    op.create_index(op.f('ix_modules_subject_id'), 'modules', ['subject_id'], unique=False)
    op.create_unique_constraint('uq_module_subject_slug', 'modules', ['subject_id', 'slug'])
    op.drop_constraint(op.f('modules_level_id_fkey'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_column('modules', 'level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('level_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_level_id_fkey'), 'modules', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_module_subject_slug', 'modules', type_='unique')
    op.drop_index(op.f('ix_modules_subject_id'), table_name='modules')
    op.create_unique_constraint(op.f('uq_module_level_slug'), 'modules', ['level_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_modules_level_id'), 'modules', ['level_id'], unique=False)
    op.drop_column('modules', 'subject_id')
    op.drop_constraint(None, 'exam_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_exam_sessions_subject_id'), table_name='exam_sessions')
    op.drop_column('exam_sessions', 'subject_id')
    op.drop_index(op.f('ix_subjects_level_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
