"""replace_mycoolpay_with_pawapay

Revision ID: 40d7bd0d0f4e
Revises: 073b0a98b8ea
Create Date: 2026-06-24 22:47:22.313604
"""
from alembic import op
import sqlalchemy as sa


revision = '40d7bd0d0f4e'
down_revision = '073b0a98b8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pawapay_deposit_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_payment_mycoolpay_ref'), 'payments', type_='unique')
    op.create_unique_constraint('uq_payment_pawapay_deposit_id', 'payments', ['pawapay_deposit_id'])
    op.drop_column('payments', 'mycoolpay_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('mycoolpay_ref', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint('uq_payment_pawapay_deposit_id', 'payments', type_='unique')
    op.create_unique_constraint(op.f('uq_payment_mycoolpay_ref'), 'payments', ['mycoolpay_ref'], postgresql_nulls_not_distinct=False)
    op.drop_column('payments', 'pawapay_deposit_id')
    # ### end Alembic commands ###
