"""add live session

Revision ID: 4fabcd4029ca
Revises: 25af0e35520d
Create Date: 2026-07-31 22:46:26.069033
"""
from alembic import op
import sqlalchemy as sa


revision = '4fabcd4029ca'
down_revision = '25af0e35520d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'preparing', 'live', 'ended', 'cancelled', name='live_session_status'), server_default='waiting', nullable=False),
    sa.Column('prep_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('examiner_notes', sa.Text(), nullable=True),
    sa.Column('notes_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_examiner_id'), 'live_sessions', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_student_id'), 'live_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_subject_id'), 'live_sessions', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_sessions_subject_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_student_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_examiner_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
