"""add image_file to questions

Revision ID: 55048e03cf39
Revises: fd80128ae8a0
Create Date: 2026-06-02 15:58:01.803443
"""
from alembic import op
import sqlalchemy as sa


revision = '55048e03cf39'
down_revision = 'fd80128ae8a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_file')
    # ### end Alembic commands ###
