"""Mise a jour du center

Revision ID: 5671a7f7775d
Revises: 69fabf446271
Create Date: 2026-07-09 06:18:56.344561
"""
from alembic import op
import sqlalchemy as sa


revision = '5671a7f7775d'
down_revision = '69fabf446271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_credit_transactions',
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('pool_balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_credit_transactions_center_id'), 'center_credit_transactions', ['center_id'], unique=False)
    op.create_index(op.f('ix_center_credit_transactions_performed_by'), 'center_credit_transactions', ['performed_by'], unique=False)
    op.create_index(op.f('ix_center_credit_transactions_student_id'), 'center_credit_transactions', ['student_id'], unique=False)
    op.add_column('centers', sa.Column('ai_credit_pool_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('centers', sa.Column('default_credits_per_student', sa.Integer(), server_default='2', nullable=False))
    op.add_column('users', sa.Column('access_duration_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_duration_days')
    op.drop_column('centers', 'default_credits_per_student')
    op.drop_column('centers', 'ai_credit_pool_balance')
    op.drop_index(op.f('ix_center_credit_transactions_student_id'), table_name='center_credit_transactions')
    op.drop_index(op.f('ix_center_credit_transactions_performed_by'), table_name='center_credit_transactions')
    op.drop_index(op.f('ix_center_credit_transactions_center_id'), table_name='center_credit_transactions')
    op.drop_table('center_credit_transactions')
    # ### end Alembic commands ###
