"""Ajout du module corrections IA

Revision ID: 589d890eb932
Revises: cda554e4e367
Create Date: 2026-05-31 03:33:37.239119
"""
from alembic import op
import sqlalchemy as sa


revision = '589d890eb932'
down_revision = 'cda554e4e367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
