"""replace_exam_id_with_level_id_payments_and_exam_access

Revision ID: 5e97b2596f11
Revises: 40d7bd0d0f4e
Create Date: 2026-06-25 03:41:19.529368
"""
from alembic import op
import sqlalchemy as sa


revision = '5e97b2596f11'
down_revision = '40d7bd0d0f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Vider exam_access et payments — données de test, pas de prod
    op.execute("DELETE FROM exam_access")
    op.execute("DELETE FROM payments")

    # exam_access
    op.add_column('exam_access', sa.Column('level_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_exam_access_exam_id'), table_name='exam_access')
    op.drop_constraint(op.f('uq_exam_access_user_exam'), 'exam_access', type_='unique')
    op.drop_constraint(op.f('exam_access_exam_id_fkey'), 'exam_access', type_='foreignkey')
    op.drop_column('exam_access', 'exam_id')
    op.alter_column('exam_access', 'level_id', nullable=False)
    op.create_index(op.f('ix_exam_access_level_id'), 'exam_access', ['level_id'], unique=False)
    op.create_unique_constraint('uq_exam_access_user_level', 'exam_access', ['user_id', 'level_id'])
    op.create_foreign_key(None, 'exam_access', 'levels', ['level_id'], ['id'], ondelete='CASCADE')

    # payments
    op.add_column('payments', sa.Column('level_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_payments_exam_id'), table_name='payments')
    op.drop_constraint(op.f('payments_exam_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'exam_id')
    op.create_index(op.f('ix_payments_level_id'), 'payments', ['level_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'levels', ['level_id'], ['id'], ondelete='RESTRICT')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_exam_id_fkey'), 'payments', 'exams', ['exam_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_payments_level_id'), table_name='payments')
    op.create_index(op.f('ix_payments_exam_id'), 'payments', ['exam_id'], unique=False)
    op.drop_column('payments', 'level_id')
    op.add_column('exam_access', sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_access', type_='foreignkey')
    op.create_foreign_key(op.f('exam_access_exam_id_fkey'), 'exam_access', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_exam_access_user_level', 'exam_access', type_='unique')
    op.drop_index(op.f('ix_exam_access_level_id'), table_name='exam_access')
    op.create_unique_constraint(op.f('uq_exam_access_user_exam'), 'exam_access', ['user_id', 'exam_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_exam_access_exam_id'), 'exam_access', ['exam_id'], unique=False)
    op.drop_column('exam_access', 'level_id')
    # ### end Alembic commands ###
