"""make_exam_plan_nullable_in_payments

Revision ID: 61d0e94eec59
Revises: 1042b1111b0f
Create Date: 2026-06-16 03:52:50.768994
"""
from alembic import op
import sqlalchemy as sa


revision = '61d0e94eec59'
down_revision = '1042b1111b0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'exam_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payments', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'exam_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
