"""Ajout des centres

Revision ID: 69fabf446271
Revises: 96aee52be729
Create Date: 2026-07-06 22:42:21.677405
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '69fabf446271'
down_revision = '96aee52be729'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Création explicite du type Enum Postgres ──────────
    # (nécessaire ici : user_role n'apparaît que dans un ADD COLUMN,
    # SQLAlchemy ne l'auto-crée pas dans ce contexte, contrairement
    # à un CREATE TABLE comme pour license_status/license_payment_method)
    postgresql.ENUM(
        'student', 'branch_secretary', 'center_director',
        name='user_role'
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_formulas',
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_center_id'), 'branches', ['center_id'], unique=False)
    op.create_table('center_licenses',
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('formula_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='license_status'), server_default='pending', nullable=False),
    sa.Column('payment_method', sa.Enum('mobile_money', 'bank_transfer', name='license_payment_method'), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['license_formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_licenses_center_id'), 'center_licenses', ['center_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_user_device_fingerprint')
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.drop_index(op.f('uq_one_active_session_per_user_exam_subject'), table_name='exam_sessions', postgresql_where="((status)::text = 'IN_PROGRESS'::text)")
    op.add_column('users', sa.Column('role', sa.Enum('student', 'branch_secretary', 'center_director', name='user_role'), server_default='student', nullable=False))
    op.add_column('users', sa.Column('center_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('target_level_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('first_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_center_id'), 'users', ['center_id'], unique=False)
    op.create_foreign_key(None, 'users', 'levels', ['target_level_id'], ['id'])
    op.create_foreign_key(None, 'users', 'centers', ['center_id'], ['id'])
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_center_id'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'access_expires_at')
    op.drop_column('users', 'first_login_at')
    op.drop_column('users', 'target_level_id')
    op.drop_column('users', 'branch_id')
    op.drop_column('users', 'center_id')
    op.drop_column('users', 'role')
    op.create_index(op.f('uq_one_active_session_per_user_exam_subject'), 'exam_sessions', ['user_id', 'exam_id', 'subject_id'], unique=True, postgresql_where="((status)::text = 'IN_PROGRESS'::text)")
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_center_licenses_center_id'), table_name='center_licenses')
    op.drop_table('center_licenses')
    op.drop_index(op.f('ix_branches_center_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('license_formulas')
    op.drop_table('centers')

    # Suppression du type Enum créé manuellement en début d'upgrade
    postgresql.ENUM(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###