"""Ajout du module A1 et A2

Revision ID: 6ffbc3074343
Revises: bf0ff7e2c9b8
Create Date: 2026-08-10 07:11:55.961493
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6ffbc3074343'
down_revision = 'bf0ff7e2c9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start_deutsch_subjects',
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_deutsch_subjects_level'), 'start_deutsch_subjects', ['level'], unique=False)
    op.create_table('start_deutsch_modules',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['start_deutsch_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_sd_module_subject_slug')
    )
    op.create_index(op.f('ix_start_deutsch_modules_subject_id'), 'start_deutsch_modules', ['subject_id'], unique=False)
    op.create_table('start_deutsch_teile',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('teil_number', sa.Integer(), nullable=False),
    sa.Column('format_type', sa.String(length=40), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('audio_file', sa.String(length=255), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['start_deutsch_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'teil_number', name='uq_sd_teil_module_number')
    )
    op.create_index(op.f('ix_start_deutsch_teile_module_id'), 'start_deutsch_teile', ['module_id'], unique=False)
    op.create_table('start_deutsch_questions',
    sa.Column('teil_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teil_id'], ['start_deutsch_teile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teil_id', 'question_number', name='uq_sd_question_teil_number')
    )
    op.create_index(op.f('ix_start_deutsch_questions_teil_id'), 'start_deutsch_questions', ['teil_id'], unique=False)
    op.create_table('start_deutsch_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['start_deutsch_subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_deutsch_sessions_subject_id'), 'start_deutsch_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_start_deutsch_sessions_user_id'), 'start_deutsch_sessions', ['user_id'], unique=False)
    op.create_table('start_deutsch_answers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['start_deutsch_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['start_deutsch_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_sd_answer_session_question')
    )
    op.create_index(op.f('ix_start_deutsch_answers_question_id'), 'start_deutsch_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_start_deutsch_answers_session_id'), 'start_deutsch_answers', ['session_id'], unique=False)
    op.create_table('start_deutsch_schreiben_corrections',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('teil_id', sa.UUID(), nullable=False),
    sa.Column('submitted_text', sa.Text(), nullable=False),
    sa.Column('criteria_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['start_deutsch_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teil_id'], ['start_deutsch_teile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_deutsch_schreiben_corrections_session_id'), 'start_deutsch_schreiben_corrections', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_start_deutsch_schreiben_corrections_session_id'), table_name='start_deutsch_schreiben_corrections')
    op.drop_table('start_deutsch_schreiben_corrections')
    op.drop_index(op.f('ix_start_deutsch_answers_session_id'), table_name='start_deutsch_answers')
    op.drop_index(op.f('ix_start_deutsch_answers_question_id'), table_name='start_deutsch_answers')
    op.drop_table('start_deutsch_answers')
    op.drop_index(op.f('ix_start_deutsch_sessions_user_id'), table_name='start_deutsch_sessions')
    op.drop_index(op.f('ix_start_deutsch_sessions_subject_id'), table_name='start_deutsch_sessions')
    op.drop_table('start_deutsch_sessions')
    op.drop_index(op.f('ix_start_deutsch_questions_teil_id'), table_name='start_deutsch_questions')
    op.drop_table('start_deutsch_questions')
    op.drop_index(op.f('ix_start_deutsch_teile_module_id'), table_name='start_deutsch_teile')
    op.drop_table('start_deutsch_teile')
    op.drop_index(op.f('ix_start_deutsch_modules_subject_id'), table_name='start_deutsch_modules')
    op.drop_table('start_deutsch_modules')
    op.drop_index(op.f('ix_start_deutsch_subjects_level'), table_name='start_deutsch_subjects')
    op.drop_table('start_deutsch_subjects')
    # ### end Alembic commands ###
