"""Ajout du module sprechen en temps reel

Revision ID: 71fd826f5381
Revises: 0ba33ac2fb38
Create Date: 2026-07-11 13:59:27.297669
"""
from alembic import op
import sqlalchemy as sa


revision = '71fd826f5381'
down_revision = '0ba33ac2fb38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
