"""add_invoice_url_to_payments

Revision ID: 96aee52be729
Revises: 1f1ca0971dc7
Create Date: 2026-06-28 05:06:13.187502
"""
from alembic import op
import sqlalchemy as sa


revision = '96aee52be729'
down_revision = '1f1ca0971dc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'invoice_url')
    # ### end Alembic commands ###
