"""Ajout du module A1 et A2, ajout de shared content

Revision ID: 9ac97293d288
Revises: 6ffbc3074343
Create Date: 2026-08-10 07:42:18.093418
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9ac97293d288'
down_revision = '6ffbc3074343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('start_deutsch_sessions', sa.Column('shared_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('start_deutsch_sessions', 'shared_content')
    # ### end Alembic commands ###
