"""Ajout du module schriben mois

Revision ID: b4312bd64aaf
Revises: 589d890eb932
Create Date: 2026-05-31 13:13:09.938779
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b4312bd64aaf'
down_revision = '589d890eb932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schreiben_subjects',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'level', 'title', name='uq_subject_provider_level_title')
    )
    op.create_index(op.f('ix_schreiben_subjects_level'), 'schreiben_subjects', ['level'], unique=False)
    op.create_index(op.f('ix_schreiben_subjects_provider'), 'schreiben_subjects', ['provider'], unique=False)
    op.create_table('corrections',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=5), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('aufgabe_score', sa.Integer(), nullable=False),
    sa.Column('kohaesion_score', sa.Integer(), nullable=False),
    sa.Column('wortschatz_score', sa.Integer(), nullable=False),
    sa.Column('grammatik_score', sa.Integer(), nullable=False),
    sa.Column('criteria_feedbacks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_feedbacks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrections_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('appreciation', sa.Text(), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_correction_session')
    )
    op.create_index(op.f('ix_corrections_session_id'), 'corrections', ['session_id'], unique=False)
    op.create_index(op.f('ix_corrections_user_id'), 'corrections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_user_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_session_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_schreiben_subjects_provider'), table_name='schreiben_subjects')
    op.drop_index(op.f('ix_schreiben_subjects_level'), table_name='schreiben_subjects')
    op.drop_table('schreiben_subjects')
    # ### end Alembic commands ###
