"""A jout de la logique enseignant et classe avec son role

Revision ID: b86a641a154e
Revises: c83d97b682d7
Create Date: 2026-08-14 06:17:48.157411
"""
from alembic import op
import sqlalchemy as sa


revision = 'b86a641a154e'
down_revision = 'c83d97b682d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_student_comments',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_student_comments_student_id'), 'teacher_student_comments', ['student_id'], unique=False)
    op.create_index(op.f('ix_teacher_student_comments_teacher_id'), 'teacher_student_comments', ['teacher_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_branch_id'), 'training_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_level_id'), 'training_sessions', ['level_id'], unique=False)
    op.create_table('training_session_students',
    sa.Column('training_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'student_id', name='uq_session_student')
    )
    op.create_index(op.f('ix_training_session_students_student_id'), 'training_session_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_training_session_students_training_session_id'), 'training_session_students', ['training_session_id'], unique=False)
    op.create_table('training_session_teachers',
    sa.Column('training_session_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'teacher_id', name='uq_session_teacher')
    )
    op.create_index(op.f('ix_training_session_teachers_teacher_id'), 'training_session_teachers', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_training_session_teachers_training_session_id'), 'training_session_teachers', ['training_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_session_teachers_training_session_id'), table_name='training_session_teachers')
    op.drop_index(op.f('ix_training_session_teachers_teacher_id'), table_name='training_session_teachers')
    op.drop_table('training_session_teachers')
    op.drop_index(op.f('ix_training_session_students_training_session_id'), table_name='training_session_students')
    op.drop_index(op.f('ix_training_session_students_student_id'), table_name='training_session_students')
    op.drop_table('training_session_students')
    op.drop_index(op.f('ix_training_sessions_level_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_branch_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_teacher_student_comments_teacher_id'), table_name='teacher_student_comments')
    op.drop_index(op.f('ix_teacher_student_comments_student_id'), table_name='teacher_student_comments')
    op.drop_table('teacher_student_comments')
    # ### end Alembic commands ###
