"""add address and logo_path to centers

Revision ID: bd7bc7271eb5
Revises: 078d27cb471f
Create Date: 2026-07-30 21:02:00.377904
"""
from alembic import op
import sqlalchemy as sa


revision = 'bd7bc7271eb5'
down_revision = '078d27cb471f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
