"""Mise a jour du modele schereiben

Revision ID: bf0ff7e2c9b8
Revises: 274741988f28
Create Date: 2026-08-04 03:11:10.103825
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf0ff7e2c9b8'
down_revision = '274741988f28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
