"""A jout de la logique enseignant et classe

Revision ID: c83d97b682d7
Revises: 52a3a8046109
Create Date: 2026-08-14 02:46:38.964367
"""
from alembic import op
import sqlalchemy as sa


revision = 'c83d97b682d7'
down_revision = '52a3a8046109'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
