"""Ajout du module sprechen en temps reele

Revision ID: c840a0a3d563
Revises: 71fd826f5381
Create Date: 2026-07-11 14:34:36.363098
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c840a0a3d563'
down_revision = '71fd826f5381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprechen_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('teile_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('live_provider_used', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprechen_sessions_student_id'), 'sprechen_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprechen_sessions_student_id'), table_name='sprechen_sessions')
    op.drop_table('sprechen_sessions')
    # ### end Alembic commands ###
