"""fix shared_content placement

Revision ID: cda9bc853c66
Revises: 9ac97293d288
Create Date: 2026-08-11 05:49:11.834587
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cda9bc853c66'
down_revision = '9ac97293d288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('start_deutsch_sessions', 'shared_content')
    op.add_column('start_deutsch_teile', sa.Column('shared_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('start_deutsch_teile', 'shared_content')
    op.add_column('start_deutsch_sessions', sa.Column('shared_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
