"""add referral_earnings table

Revision ID: d8810f99fc3d
Revises: a02875690227
Create Date: 2026-07-17 02:04:39.886981
"""
from alembic import op
import sqlalchemy as sa


revision = 'd8810f99fc3d'
down_revision = 'a02875690227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_earnings',
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', name='uq_referral_earning_payment')
    )
    op.create_index(op.f('ix_referral_earnings_referred_user_id'), 'referral_earnings', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referral_earnings_referrer_user_id'), 'referral_earnings', ['referrer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_earnings_referrer_user_id'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_referred_user_id'), table_name='referral_earnings')
    op.drop_table('referral_earnings')
    # ### end Alembic commands ###
