"""add_app_settings_table

Revision ID: ea79ac6db012
Revises: f855e0fd35e9
Create Date: 2026-06-26 08:20:05.962729
"""
from alembic import op
import sqlalchemy as sa


revision = 'ea79ac6db012'
down_revision = 'f855e0fd35e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
