"""Ajout de subject_number

Revision ID: f21b999259db
Revises: cda9bc853c66
Create Date: 2026-08-11 11:22:51.238380
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f21b999259db'
down_revision = 'cda9bc853c66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('start_deutsch_subjects', sa.Column('subject_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_sd_subject_level_number', 'start_deutsch_subjects', ['level', 'subject_number'])
    op.drop_column('start_deutsch_teile', 'shared_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('start_deutsch_teile', sa.Column('shared_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_sd_subject_level_number', 'start_deutsch_subjects', type_='unique')
    op.drop_column('start_deutsch_subjects', 'subject_number')
    # ### end Alembic commands ###
