/* Hand-written — mirrors app/modules/live_session/router.py's inline
 * message shapes. NOT generated by openapi-typescript-codegen: WebSocket
 * routes are never part of the OpenAPI spec, so these types have no
 * automatic source of truth. Keep this file in sync manually whenever
 * router.py's message shapes change.
 *
 * The REST-only types (LiveSessionResponse, LiveSessionListResponse,
 * CreateLiveSessionRequest, SubmitNotesRequest) ARE auto-generated
 * already (see ../models/) — not duplicated here.
 */

// ── Inbound: frontend -> backend (sent as WebSocket text frames) ──

export interface ReadyToStartMessage {
  type: 'ready_to_start';
}

export interface EndSessionMessage {
  type: 'end_session';
}

/** Chat texte — relayé brut par le backend au pair, jamais persisté. */
export interface ChatMessageInbound {
  type: 'chat_message';
  text: string;
}

export type LiveSessionInboundMessage =
  | ReadyToStartMessage
  | EndSessionMessage
  | ChatMessageInbound;

// ── Outbound: backend -> frontend (received as WebSocket text frames;
//    binary frames carry raw PCM16 audio and aren't typed here) ──

export interface PreparationStartedEvent {
  type: 'preparation_started';
  duration_minutes: number;
}

export interface LiveStartedEvent {
  type: 'live_started';
}

export interface PeerLeftEvent {
  type: 'peer_left';
}

/** Chat texte reçu du pair — le backend attache lui-même `from` au
 * relais (jamais fourni par le client émetteur), donc cette valeur est
 * fiable côté réception. */
export interface ChatMessageEvent {
  type: 'chat_message';
  text: string;
  from: 'student' | 'examiner';
}

export type LiveSessionOutboundEvent =
  | PreparationStartedEvent
  | LiveStartedEvent
  | PeerLeftEvent
  | ChatMessageEvent;

// ── Type guard helper, since every message arrives as unknown JSON ──

export function parseLiveSessionMessage(raw: string): LiveSessionOutboundEvent {
  return JSON.parse(raw) as LiveSessionOutboundEvent;
}