/* Hand-written — mirrors app/modules/sprechen_agent/schemas.py.
 * NOT generated by openapi-typescript-codegen: WebSocket routes are
 * never part of the OpenAPI spec, so these types have no automatic
 * source of truth. Keep this file in sync manually whenever
 * schemas.py's Inbound/Outbound message shapes change.
 *
 * The REST-only types (SessionHistoryItem, SessionHistoryListResponse)
 * ARE auto-generated already (see ../models/) — not duplicated here.
 */

// ── Inbound: frontend -> backend (sent as WebSocket text frames) ──

export interface AudioChunkMessage {
  type: 'audio_chunk';
  session_id: string;
  sequence_number: number;
}

export interface EndTurnMessage {
  type: 'end_turn';
  session_id: string;
}

export interface AbandonSessionMessage {
  type: 'abandon_session';
  session_id: string;
}

export interface ReadyToStartMessage {
  type: 'ready_to_start';
  session_id: string;
}

export type InboundMessage =
  | AudioChunkMessage
  | EndTurnMessage
  | AbandonSessionMessage
  | ReadyToStartMessage;

// ── Outbound: backend -> frontend (received as WebSocket text frames;
//    binary frames carry raw PCM16 audio and aren't typed here) ──

export interface SessionReadyEvent {
  type: 'session_ready';
  session_id: string;
  total_teile: number;
  first_teil_name: string;
}

export interface PreparationStartedEvent {
  type: 'preparation_started';
  session_id: string;
  teil_number: number;
  teil_name: string;
  instructions: string;
  content_points: string[];
  themes: Record<string, ThemeOption> | null;
  preparation_minutes: number;
}

export interface TeilStartedEvent {
  type: 'teil_started';
  session_id: string;
  teil_number: number;
  teil_name: string;
  instructions: string;
  content_points: string[];
  themes: Record<string, ThemeOption> | null;
  duration_minutes: number;
  preparation_minutes: number;
}

// Shape of one theme choice — covers both observed variants:
// telc-style "titel" + "leitpunkte", and Goethe-style "title" + "leitpunkte".
// Both field name variants are optional since the backend passes the
// raw JSON through as-is without renaming keys.
export interface ThemeOption {
  title?: string;
  titel?: string;
  leitpunkte?: string[];
  punkte?: string[];
  accroche?: string;
}

export interface AgentSpeakingEvent {
  type: 'agent_speaking';
  session_id: string;
}

export interface StudentTurnEvent {
  type: 'student_turn';
  session_id: string;
}

export interface TranscriptUpdateEvent {
  type: 'transcript_update';
  session_id: string;
  speaker: 'student' | 'agent';
  text: string;
}

export interface SessionEndedEvent {
  type: 'session_ended';
  session_id: string;
  reason: 'completed' | 'abandoned' | 'error';
}

export type OutboundEvent =
  | SessionReadyEvent
  | PreparationStartedEvent
  | TeilStartedEvent
  | AgentSpeakingEvent
  | StudentTurnEvent
  | TranscriptUpdateEvent
  | SessionEndedEvent;

// ── Grading — pushed as a final text frame, type: 'grading_result',
//    with the payload spread alongside it (see router.py) ──

export interface CriterionScoreOut {
  criterion_name: string;
  score: number;
  max_score: number;
  issue: string | null;
  model_phrase: string | null;
  tip: string | null;
}

export interface TeilGradingOut {
  teil_number: number;
  teil_name: string;
  criteria: CriterionScoreOut[];
  teil_score: number;
  teil_max_score: number;
}

export interface GradingResultMessage {
  type: 'grading_result';
  session_id: string;
  provider: string;
  level: string;
  teile: TeilGradingOut[];
  total_score: number;
  total_max_score: number;
  passed: boolean;
  strengths: string[];
  improvement_areas: string[];
  graded_at: string;
  previous_score_percent: number | null;
  score_delta_percent: number | null;
}

// ── Type guard helper, since every message arrives as unknown JSON ──

export function parseOutboundMessage(
  raw: string
): OutboundEvent | GradingResultMessage {
  return JSON.parse(raw) as OutboundEvent | GradingResultMessage;
}